import React from "react";

type UserProps = {};

export const metadata = {
  title: "User",
  description: "Generated by create next app",
};

const User: React.FC<UserProps> = () => {
  return <div>User Page</div>;
};
export default User;
