import { getProduct } from "@/actions/getProduct";
import Container from "@/common/Container";
import { Hydrate, dehydrate } from "@tanstack/react-query";
import React from "react";
import getQueryClient from "../../components/getQueryClient";
import ProductDetail from "./components/ProductDetail";

type ProductDetailProps = {
  params: {
    productId: string;
  };
};

export const metadata = {
  title: "Product Detail",
  description: "Generated by create next app",
};

const ProductDetailPage: React.FC<ProductDetailProps> = async ({ params }) => {
  const { productId } = params;
  const queryClient = getQueryClient();
  await queryClient.prefetchQuery({
    queryKey: ["product", productId],
    queryFn: () => getProduct(productId),
  });
  const dehydrateState = dehydrate(queryClient);
  return (
    <Hydrate state={dehydrateState}>
      <Container>
        <main className="p-6 space-y-5 min-h-full">
          {/* <h1 className="text-4xl font-bold">Products Detail</h1> */}
          <ProductDetail id={productId}/>
        </main>
      </Container>
    </Hydrate>
  );
};
export default ProductDetailPage;
