import Navbar from "@/common/Navbar";
import { UIProvider } from "@/providers/NextUIProvider";
import { ReactQueryProvider } from "@/providers/ReactQuery";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../globals.css";
import { Toaster } from "react-hot-toast";
import BarProvider from "@/providers/ProgressBarProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "wondrMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <BarProvider>
          <ReactQueryProvider>
            <UIProvider>
              <Navbar />
              {children}
              <Toaster
                position="bottom-center"
                reverseOrder={false}
              />
            </UIProvider>
          </ReactQueryProvider>
        </BarProvider>
      </body>
    </html>
  );
}
