import { Button } from "@nextui-org/button";
import Container from "@/common/Container";
import React from "react";

type CartProps = {};

export const metadata = {
  title: "Cart",
  description: "Generated by create next app",
};

const Cart: React.FC<CartProps> = () => {
  return (
    <div className="">
      <Container>
        <div className="px-4 py-16 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold">Shopping Cart</h1>
          <Button>Click me</Button>
        </div>
      </Container>
    </div>
  );
};
export default Cart;
