import Navbar from "@/common/Navbar";
import { UIProvider } from "@/providers/NextUIProvider";
import { ReactQueryProvider } from "@/providers/ReactQuery";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { AuthUserProvider } from "@/providers/authUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "wondrMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <ReactQueryProvider>
          <UIProvider>
            <AuthUserProvider>
              <Navbar />
              {children}
            </AuthUserProvider>
          </UIProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
