import Container from "@/common/Container";
import CartDetail from "./components/CartDetail";

export const metadata = {
  title: "Cart",
  description: "Generated by create next app",
};

const Cart = () => {
  return (
    <Container>
      <div className="px-2 py-5 md:py-10 sm:px-6 lg:px-8">
        <CartDetail />
      </div>
    </Container>
  );
};
export default Cart;
