import Container from "@/common/Container";
import CartDetail from "./components/CartDetail";

export const metadata = {
  title: "Cart",
  description: "Generated by create next app",
};

const Cart = () => {
  return (
    <Container>
      <div className="p-3 md:py-10">
        <CartDetail />
      </div>
    </Container>
  );
};
export default Cart;
