import React from "react";

type ProductDetailProps = {};

export const metadata = {
  title: "Product Detail",
  description: "Generated by create next app",
};

const ProductDetail: React.FC<ProductDetailProps> = () => {
  return <div>ProductDetail Page</div>;
};
export default ProductDetail;
