import Container from "@/common/Container";
import React from "react";
import ImageGallery from "./components/ImageGallery";
import ProductDetailSection from "./components/ProductDetail";
import CardCTA from "./components/CTA/Card";

type ProductDetailProps = {};

export const metadata = {
  title: "Product Detail",
  description: "Generated by create next app",
};

const ProductDetail: React.FC<ProductDetailProps> = () => {
  return (
    <Container>
      <main className="p-6 space-y-5">
        {/* <h1 className="text-4xl font-bold">Products Detail</h1> */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
          {/* white overlay background applied to hide the empty space because of the grid */}
          <section className="shadow-gray-300 shadow-2xl bg-white rounded-lg">
            <ImageGallery />
          </section>
          <section className="mt-5 space-y-3 flex-1 lg:col-span-2">
            <ProductDetailSection />
          </section>
          <section className="hidden lg:block">
            <CardCTA/>
          </section>
        </div>
      </main>
    </Container>
  );
};
export default ProductDetail;
